
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN ID INT NUM SEMICOLstatement : INT ID ASSIGN NUM SEMICOL'
    
_lr_action_items = {'INT':([0,],[2,]),'$end':([1,6,],[0,-1,]),'ID':([2,],[3,]),'ASSIGN':([3,],[4,]),'NUM':([4,],[5,]),'SEMICOL':([5,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> INT ID ASSIGN NUM SEMICOL','statement',5,'p_statement_assign','analysis.py',32),
]
